version: "3.3"


services:
   cache:
      image: nginx
      networks:
        - func
      volumes:
       - ./html:/usr/share/nginx/html
       - ./nginx.conf:/etc/nginx/nginx.conf
      ports:
       - "80:80"
      environment:
       - NGINX_HOST=foobar.com
       - NGINX_PORT=80
      deploy:
         mode: global
         restart_policy:
                condition: on-failure
                delay: 5s
                window: 380s
         placement:
                constraints:
                    - 'node.role == manager'
                    - 'node.platform.os == linux'
         resources:
                limits:
                    memory: 500M

networks:
   func:
      external:
        name: func_functions
