provider:
  name: faas
  gateway: http://127.0.0.1:8080

functions:
  # Gateway to handle the UI and API request
  file-handler:
    lang: dockerfile
    handler: ./file_handler
    image: s8sg/file-handler:latest

  image-resizer:
    lang: dockerfile
    handler: ./ResizeImage
    image: s8sg/resizer:latest

  file-uploader:
    lang: dockerfile
    handler: ./file_uploader
    image: s8sg/file-uploader:latest
